### ISSUE TITLE
FrankenGAN with chordatlas - bikeGAN root not found

### ISSUE THREAD

**Issue by joleek** [twak/chordatlas#13] opened 2018-12-15 00:51 UTC
I'm trying to run FrankenGAN (from docker) with chordatlas, but for some reason the textures are not loading like in the [video](https://www.youtube.com/watch?v=Jz8q09r-RFg&feature=youtu.be&t=1m32s).

I ran `nvidia-docker run -v input:/home/user/bikegan/input -v output:/home/user/bikegan/output -it --rm twak/bikegan` in a folder `bikegan-temp`, and I see the following output (I truncated lines from the top):
```
model [BiCycleGANModel] was created
Loading model bicycle_gan...
---------- Networks initialized -------------
[network super6 is awaiting input]
initialization method [xavier]
initialization method [xavier]
-----------------------------------------------
model [BiCycleGANModel] was created
all nets up
[network super10 is awaiting input]
```
If I check with `nvidia-smi`, I also see that `/home/user/bikegan/test_interactive.py` is actively running.

I leave the bikeGAN terminal untouched so the network can keep running. All other work is run on separate terminals.

At this point, if I check my `bikegan-temp` folder, I see that there is nothing there.

I followed the instructions and added the path to my `bikegan-temp` folder as my bikeGAN root in the settings menu. However, if I follow the steps in the aforementioned video or as [the workflow here](https://github.com/twak/chordatlas/wiki/frankenGAN-details), I just see this output:

```
computing BuildingApp
batch 0/1 
finished 1 BuildingApps
computing FacadeLabelApp
batch 0/6 
timeout trying to get bikeGAN result 16059761037757--0.021439835879290325. 
is bikeGAN running? 
has bikeGAN root been set correctly in the settings menu? ([full path omitted]/bikegan-temp
time taken 10171
```

At this point, if I check my `bikegan-temp` folder, I see that it contains an `input` folder. The structure of the folder are as follows:
- `facade labels`
  - `val`
     - `go`, which contains "16059761037757--0.021439835879290325"
     - a bunch of stuff that looks like 0ad7a36a-7a2f-457e-9b96-90ad3e6d94de@0.14698090781865863_0.0_0.0_0.0_0.0_0.0_0.0_0.0_0.0.png
- `facade labels_empty`
  - `val`
     - a bunch of stuff that looks like 0ad7a36a-7a2f-457e-9b96-90ad3e6d94de@0.14698090781865863_0.0_0.0_0.0_0.0_0.0_0.0_0.0_0.0.png

There is also no `output` folder created in my bikeGAN root, which I thought was weird, especially since in [the code where the error text is printed](https://github.com/twak/chordatlas/blob/master/src/org/twak/viewTrace/franken/Pix2Pix.java) there seems to be some outDir that we expect to be created.

Is this the correct workflow I'm supposed to be following, or am I missing something?

**Comment by twak** [comment] 2018-12-15 12:14
Hi, thanks for reporting this. Yes, this sounds like the correct workflow.

The `png` files with the strange names are the inputs that chordatlas writes out for bikegan to process. Once the `go` file is written, bikegan should automatically i) process these to outputs, ii) delete the `go` file and inputs, and iii) write the output to the bikegan output folder.

Some questions (if you don't want to post then answers on a public forum, email me:

1/ What is the (exact) bikegan root that you set in chordatlas?
2/ Which operating system are you using?
3/ After the inputs are written, is there any additional output from bikegan?

**Comment by twak** [comment] 2018-12-18 12:01
One more thought I had while cycling to work: you must have to docker (or nvidia-docker) running as the same user as chordatlas. (i.e. you shouldn't be running docker with `sudo`). You can add your user to the same group with these [instructions](https://docs.docker.com/install/linux/linux-postinstall/). You then have to restart your computer.

This is because bikegan uses python's `watchdog` to listen for new input, and it doesn't work across users under docker. This probably means the docker version won't work under windows :(

**Comment by twak** [comment] 2019-01-24 14:27
No comment back for a month; closing issue :(

**Comment by joleek** [comment] 2019-02-04 19:53
Sorry about the delay - was on extended vacation. I have a suspicion that the error is due to the machine that I am constrained under, and I am trying to move the code over to another machine. Will let you know if a problem still exists!

**Comment by joleek** [comment] 2019-02-13 20:39
I have moved to a system with no constraints but this problem seems to persist - would you be fine if we reopened the issue?

I am not running docker with sudo - I am running as kwlee (me), which I have put into the docker group.

To answer your questions:
1) The exact BikeGAN root that I am using is (and I have read / write permissions in this directory) `/home/kwlee/bikegan_temp`.  (I have also tried `/home/kwlee/bikegan_temp/` with the extra slash in the end, if that makes a difference)
2) My system is Ubuntu 14.04.5 LTS.
3) there are no additional outputs from bikeGAN beyond the following:
```
model [BiCycleGANModel] was created
all nets up
[network super10 is awaiting input]
```

If I run `ps aux | grep "test_interactive.py"`, I see the following: 
`1000     25356  4.8  3.5 49243592 2339560 pts/0 Sl+ 15:33   0:09 python /home/user/bikegan/test_interactive.py`
which means that user 1000 is running the script, not me. Does that make a difference?

I also have a feeling that this may be related to [this issue](https://github.com/twak/bikegan/issues/1) that I opened on BikeGAN. Perhaps my solution of using relative path names is causing more problems than I expected.

**Comment by twak** [comment] 2019-02-14 11:21
Hey, hope you had a great holiday! Yes it would be great to get to understand what is happening.

I have a clean ubuntu install at home; I'll try to reproduce your workflow tonight.

**Comment by joleek** [comment] 2019-02-14 21:57
I ran the same system without nvidia-docker according to instructions [here](https://github.com/twak/bikegan) and it worked perfectly! Perhaps it is a problem with permission settings with docker then.

**Comment by twak** [comment] 2019-02-15 13:29
Great that you got it to work! If you use the project for anything, I'd love to know - it all helps with future funding etc..

I found a couple of issues with the docker container, so I rebuilt it...I'm not certain these were causing your problems though. 

Two thoughts:

-  I notice that you omitted the `pwd` bit when starting the docker container - when I tried this, docker didn't deal well with relative paths
- The `input` and `output` folders need to exist before you start the container. When the container starts it should populate `input` with the different input points for the networks. I updated the instructions to make this clear.

It would be great if you can test my new image. Create a new temporary director, `cd` into it, and run
```
mkdir input output
nvidia-docker run -v $(pwd)/input:/home/user/bikegan/input -v $(pwd)/output:/home/user/bikegan/output -it --rm twak/bikegan
```

I can run docker with sudo fine now, so I don't think this is the problem.

**Comment by joleek** [comment] 2019-02-21 16:21
I tried the new image and I'm still running into the same issue described [here](https://github.com/twak/bikegan/issues/1), where I get many permission denied errors. If I remove the $(pwd) bit, that doesn't give the permission denied errors, but then the script hangs as describes. Let me know if any more information about my system would be helpful!

**Comment by twak** [comment] 2019-02-21 18:53
thanks for trying - do both the `input` and `output` folders exist before you start the image? If I don't create input and output I get similar error messages:

```
PermissionError: [Errno 13] Permission denied: './input/door textures'
```

Then it creates the folders with the **wrong** permissions (root). `ls -la` gives:

```
drwxr-xr-x 56 twak twak 4096 Feb 21 18:34 ..
drwxr-xr-x  2 root root 4096 Feb 21 18:45 input
drwxr-xr-x  2 root root 4096 Feb 21 18:45 output
```

Further runs cannot write to these folders (and I guess neither can chordatlas).

if I do `sudo rm -rf input output`, then `mkdir input output` (from your non-root account), it works.

In other news, if I run without pwd (`nvidia-docker run -v input:/home/user/bikegan/input -v output:/home/user/bikegan/output -it --rm twak/bikegan`) it doesn't create input, or output, in the current directory, so I don't know where the output would go!

**Comment by twak** [comment] 2019-03-05 18:04
I'm going to assume that the previous reply fixed the problem. Shout if this is still an issue...I can't reproduce it any other way.

**Closed as completed by twak** 2019-03-05 18:04 UTC
