### ISSUE TITLE
windows build fails to find CRS EPSG:27700

### ISSUE THREAD

**Issue by chenkl1995** [twak/chordatlas#12] opened 2018-12-03 15:45 UTC
Follow given build instructions with 2 changes(on Windows):
- ![tmp1](https://user-images.githubusercontent.com/15438055/49384102-419eb100-f755-11e8-97db-a68ddcfa398f.JPG)
- ![tmp2](https://user-images.githubusercontent.com/15438055/49384130-4f543680-f755-11e8-8450-a623b3b4e90c.JPG)

I have built the program successfully, but when I run it, the program shows the error `coordinate system error -- failed to find CRS EPSG:27700` and the cmd shows `java.lang.NoClassDefFoundError: org/hsqldb/jdbc/JDBCDataSource`, can you help me the solve this problem?
Thank you!

**Comment by twak** [comment] 2018-12-03 23:38
Hi! does the provided binary run for you? Do you get the error without the changes? Why do you need to make the changes.

How are you running (from the jar, or from an IDE)?

The coordinate system errors are probably from geotools - I have had a few issues with dependency order.  This is strange because the changes you show wouldn't have affected geotools!

**Comment by twak** [comment] 2018-12-03 23:40
This line is the patch in the POM that was required to fix geotools. Could anything have affected the geotools package order?
https://github.com/twak/chordatlas/blob/master/pom.xml#L12

**Comment by chenkl1995** [comment] 2018-12-04 03:16
Thanks for your reply.
- The provided binary can run correctly.
- I add the `<version>3.5.1</version>` because without it when I execute `mvn package` the cmd shows
![tmp3](https://user-images.githubusercontent.com/15438055/49415905-16e34580-f7b3-11e8-90ea-e1a0c195fe0f.JPG). After add this, it can build successfully
- The reason for the `751` --> `752` is the official `gurobi` website offers only the 752 version
-  I run the program from the jar on cmd

**Comment by twak** [comment] 2018-12-04 06:44
Thanks for the info. 

I agree that gurobi needs to be updated, and I have run with 752 without problems, so I don't think that's the problem.

For the mvn compiler plugin, are you sure that you don't have a corrupt maven cache?:
https://stackoverflow.com/questions/7631949/failed-to-parse-plugin-descriptor-for-org-apache-maven-pluginsmaven-resources-p

Otherwise, I am traveling for 2 weeks, I will try to reproduce your issue when I get home....

**Comment by chenkl1995** [comment] 2018-12-04 07:52
Yeah, I think it is a corrupt maven cache. After I delete it and re-run, the program can compile without adding the <version>3.5.1</version>. But the program shows again the error coordinate system error -- failed to find CRS EPSG:27700.
Then I try to build the system on ubuntu, follow the same instrutions and it works normally. Thanks for your quick reply.
Otherwise, I have a question about the `model-material-joint`, does it take the real image(such as building facade image) as input?

**Comment by twak** [comment] 2018-12-04 07:58
Ah, okay so it's a windows problem? that is super strange. The jar was built on ubuntu - so you could build on ubuntu and run on windows?

I'll take a look when I get home to my windows dev machine.

**Comment by chenkl1995** [comment] 2018-12-04 08:14
Yeah, I can build it on ubuntu and run both on windows and ubuntu.

**Comment by twak** [comment] 2018-12-23 11:29
I can't reproduce this on my windows. Can I check i) which exact version of Java are you using (say 1.8.191), and ii) which version of mvn? 

I've just tried it on Sun's jdk 1.8.0_131, with maven 3.6.0. `mvn package` worked as expected. I was able to import the glasgow gml file.

**Comment by chenkl1995** [comment] 2018-12-24 07:25
On windows, the version of Java is 1.8.0_144 with maven 3.6.0.
![maven_java](https://user-images.githubusercontent.com/15438055/50393279-1aedfc00-0790-11e9-954f-7fc3c61b93ac.JPG)

**Comment by twak** [comment] 2018-12-24 13:12
I've requested that version of Java from the University of Leeds IT department. I'll try to reproduce when they install it. The IT service backlog is currently 23 days...so this may take some time...

![image](https://user-images.githubusercontent.com/127402/50400279-6ba82980-077d-11e9-92d2-1ebaf7a9cab1.png)

**Comment by twak** [comment] 2019-02-04 14:54
IT finally installed java 8.144, and I am still unable to reproduce this issue with the latest chordatlas.

Is it possible to try again in a clean environment, and send me the full mvn build logs?

**Comment by twak** [comment] 2019-02-15 13:31
Can't reproduce + no update for a while + research code = closing issue after a month

**Closed as completed by twak** 2019-02-15 13:31 UTC
